// ASK-GPT Discover — Trusted Source List
// api/_lib/discoverSources.ts
// Only source definitions. No fetching, parsing, or caching here.

// ── Types ─────────────────────────────────────────────────────────────────────

export type DiscoverTab = 'foryou' | 'bangladesh';
export type DiscoverLanguage = 'en' | 'bn';
export type DiscoverRegion = 'global' | 'bangladesh';

export type DiscoverSource = {
  id: string;
  tab: DiscoverTab;
  label: string;
  feedUrl: string;
  language: DiscoverLanguage;
  region: DiscoverRegion;
  category: string;
  priority: number;
  trustScore: number;
};

// ── Google News RSS helper ────────────────────────────────────────────────────

function googleNewsSearch(
  query: string,
  options: { language: DiscoverLanguage; region: DiscoverRegion },
): string {
  if (options.language === 'bn') {
    return `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=bn&gl=BD&ceid=BD:bn`;
  }
  return `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US:en`;
}

// ── Source List ───────────────────────────────────────────────────────────────

export const DISCOVER_SOURCES: DiscoverSource[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // FOR YOU — Global English
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'foryou_world_reuters',
    tab: 'foryou',
    label: 'Reuters — World News',
    feedUrl: 'https://feeds.reuters.com/reuters/topNews',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 100,
    trustScore: 98,
  },
  {
    id: 'foryou_world_bbc',
    tab: 'foryou',
    label: 'BBC News — World',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 99,
    trustScore: 97,
  },
  {
    id: 'foryou_world_ap',
    tab: 'foryou',
    label: 'AP News — Top Stories',
    feedUrl: googleNewsSearch('site:apnews.com', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 98,
    trustScore: 97,
  },
  {
    id: 'foryou_tech_verge',
    tab: 'foryou',
    label: 'The Verge — Technology',
    feedUrl: 'https://www.theverge.com/rss/index.xml',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 95,
    trustScore: 93,
  },
  {
    id: 'foryou_tech_techcrunch',
    tab: 'foryou',
    label: 'TechCrunch',
    feedUrl: 'https://techcrunch.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 94,
    trustScore: 92,
  },
  {
    id: 'foryou_ai_wired',
    tab: 'foryou',
    label: 'Wired — AI & Science',
    feedUrl: 'https://www.wired.com/feed/rss',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 93,
    trustScore: 91,
  },
  {
    id: 'foryou_ai_gnews',
    tab: 'foryou',
    label: 'Google News — Artificial Intelligence',
    feedUrl: googleNewsSearch('artificial intelligence AI OpenAI Google DeepMind', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 92,
    trustScore: 88,
  },
  {
    id: 'foryou_business_bloomberg',
    tab: 'foryou',
    label: 'Bloomberg — Business',
    feedUrl: googleNewsSearch('site:bloomberg.com business economy', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 91,
    trustScore: 95,
  },
  {
    id: 'foryou_finance_cnbc',
    tab: 'foryou',
    label: 'CNBC — Markets & Finance',
    feedUrl: 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
    language: 'en',
    region: 'global',
    category: 'finance',
    priority: 90,
    trustScore: 93,
  },
  {
    id: 'foryou_science_daily',
    tab: 'foryou',
    label: 'ScienceDaily — Top Science',
    feedUrl: 'https://www.sciencedaily.com/rss/top/science.xml',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 88,
    trustScore: 90,
  },
  {
    id: 'foryou_health_who',
    tab: 'foryou',
    label: 'Google News — Health & Medicine',
    feedUrl: googleNewsSearch('health medicine WHO CDC disease treatment', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 87,
    trustScore: 88,
  },
  {
    id: 'foryou_sports_espn',
    tab: 'foryou',
    label: 'ESPN — Sports',
    feedUrl: 'https://www.espn.com/espn/rss/news',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 86,
    trustScore: 90,
  },
  {
    id: 'foryou_entertainment_variety',
    tab: 'foryou',
    label: 'Variety — Entertainment',
    feedUrl: 'https://variety.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 84,
    trustScore: 87,
  },
  {
    id: 'foryou_culture_gnews',
    tab: 'foryou',
    label: 'Google News — Culture & Society',
    feedUrl: googleNewsSearch('culture society lifestyle trending stories', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 82,
    trustScore: 82,
  },
  {
    id: 'foryou_climate_gnews',
    tab: 'foryou',
    label: 'Google News — Climate & Environment',
    feedUrl: googleNewsSearch('climate change environment nature sustainability', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 80,
    trustScore: 85,
  },
  {
    id: 'foryou_world_bbc_frontpage',
    tab: 'foryou',
    label: 'BBC News — Top Stories',
    feedUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 95,
  },
  {
    id: 'foryou_world_bbc_world',
    tab: 'foryou',
    label: 'BBC News — World',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 95,
  },
  {
    id: 'foryou_world_guardian',
    tab: 'foryou',
    label: 'The Guardian — World',
    feedUrl: 'https://www.theguardian.com/world/rss',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 94,
  },
  {
    id: 'foryou_business_guardian',
    tab: 'foryou',
    label: 'The Guardian — Business',
    feedUrl: 'https://www.theguardian.com/business/rss',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 93,
  },
  {
    id: 'foryou_tech_guardian',
    tab: 'foryou',
    label: 'The Guardian — Technology',
    feedUrl: 'https://www.theguardian.com/technology/rss',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_science_guardian',
    tab: 'foryou',
    label: 'The Guardian — Science',
    feedUrl: 'https://www.theguardian.com/science/rss',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_sports_guardian',
    tab: 'foryou',
    label: 'The Guardian — Sport',
    feedUrl: 'https://www.theguardian.com/sport/rss',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_culture_guardian',
    tab: 'foryou',
    label: 'The Guardian — Culture',
    feedUrl: 'https://www.theguardian.com/culture/rss',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_education_guardian',
    tab: 'foryou',
    label: 'The Guardian — Education',
    feedUrl: 'https://www.theguardian.com/education/rss',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_climate_guardian',
    tab: 'foryou',
    label: 'The Guardian — Environment',
    feedUrl: 'https://www.theguardian.com/environment/rss',
    language: 'en',
    region: 'global',
    category: 'climate',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_world_aljazeera_all',
    tab: 'foryou',
    label: 'Al Jazeera — Latest',
    feedUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_world_dw_all',
    tab: 'foryou',
    label: 'DW — Latest',
    feedUrl: 'https://rss.dw.com/rdf/rss-en-all',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_world_france24',
    tab: 'foryou',
    label: 'France 24 — English',
    feedUrl: 'https://www.france24.com/en/rss',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_world_npr_news',
    tab: 'foryou',
    label: 'NPR — News',
    feedUrl: 'https://feeds.npr.org/1001/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_politics_npr',
    tab: 'foryou',
    label: 'NPR — Politics',
    feedUrl: 'https://feeds.npr.org/1014/rss.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_tech_engadget',
    tab: 'foryou',
    label: 'Engadget — Technology',
    feedUrl: 'https://www.engadget.com/rss.xml',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_tech_arstechnica',
    tab: 'foryou',
    label: 'Ars Technica',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/index',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_ai_venturebeat',
    tab: 'foryou',
    label: 'VentureBeat — AI',
    feedUrl: 'https://venturebeat.com/category/ai/feed/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_science_sciencedaily',
    tab: 'foryou',
    label: 'ScienceDaily — Top Science',
    feedUrl: 'https://www.sciencedaily.com/rss/top/science.xml',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_science_space',
    tab: 'foryou',
    label: 'Space.com',
    feedUrl: 'https://www.space.com/feeds/all',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_sports_bbc',
    tab: 'foryou',
    label: 'BBC Sport',
    feedUrl: 'https://feeds.bbci.co.uk/sport/rss.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_sports_espncricinfo',
    tab: 'foryou',
    label: 'ESPN Cricinfo',
    feedUrl: 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_sports_espn',
    tab: 'foryou',
    label: 'ESPN — Sports',
    feedUrl: 'https://www.espn.com/espn/rss/news',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_entertainment_variety',
    tab: 'foryou',
    label: 'Variety — Entertainment',
    feedUrl: 'https://variety.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_entertainment_hollywoodreporter',
    tab: 'foryou',
    label: 'The Hollywood Reporter',
    feedUrl: 'https://www.hollywoodreporter.com/t/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_entertainment_deadline',
    tab: 'foryou',
    label: 'Deadline — Entertainment',
    feedUrl: 'https://deadline.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_music_rollingstone',
    tab: 'foryou',
    label: 'Rolling Stone',
    feedUrl: 'https://www.rollingstone.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_gaming_ign',
    tab: 'foryou',
    label: 'IGN — Gaming',
    feedUrl: 'https://feeds.ign.com/ign/all',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_culture_smithsonian',
    tab: 'foryou',
    label: 'Smithsonian Magazine',
    feedUrl: 'https://www.smithsonianmag.com/rss/latest_articles/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_career_hbr',
    tab: 'foryou',
    label: 'Harvard Business Review',
    feedUrl: 'https://hbr.org/feed',
    language: 'en',
    region: 'global',
    category: 'careers',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_politics_politico',
    tab: 'foryou',
    label: 'Politico',
    feedUrl: 'https://www.politico.com/rss/politicopicks.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_wsj',
    tab: 'foryou',
    label: 'The Wall Street Journal',
    feedUrl: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_world_time',
    tab: 'foryou',
    label: 'TIME',
    feedUrl: 'https://rss.time.com/web/time/rss/top/index.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_tech_mitnews',
    tab: 'foryou',
    label: 'MIT News',
    feedUrl: 'https://news.mit.edu/rss/feed',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_ai_fastcompany',
    tab: 'foryou',
    label: 'Fast Company',
    feedUrl: 'https://www.fastcompany.com/rss',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_science_nasa',
    tab: 'foryou',
    label: 'NASA',
    feedUrl: 'https://www.nasa.gov/news-release/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_sports_skysports',
    tab: 'foryou',
    label: 'Sky Sports',
    feedUrl: 'https://www.skysports.com/rss/12040',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_entertainment_billboard',
    tab: 'foryou',
    label: 'Billboard',
    feedUrl: 'https://www.billboard.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_education_edsurge',
    tab: 'foryou',
    label: 'EdSurge',
    feedUrl: 'https://www.edsurge.com/articles_rss',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_vox',
    tab: 'foryou',
    label: 'Vox',
    feedUrl: 'https://www.vox.com/rss/index.xml',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 88,
  },

  {
    id: 'foryou_politics_thehill',
    tab: 'foryou',
    label: 'The Hill',
    feedUrl: 'https://thehill.com/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_company_marketwatch',
    tab: 'foryou',
    label: 'MarketWatch',
    feedUrl: 'https://feeds.marketwatch.com/marketwatch/topstories/',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_world_cbc',
    tab: 'foryou',
    label: 'CBC News',
    feedUrl: 'https://www.cbc.ca/cmlink/rss-topstories',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_tech_9to5google',
    tab: 'foryou',
    label: '9to5Google',
    feedUrl: 'https://9to5google.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_startups_businessinsider',
    tab: 'foryou',
    label: 'Business Insider',
    feedUrl: 'https://www.businessinsider.com/rss',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_science_scientificamerican',
    tab: 'foryou',
    label: 'Scientific American',
    feedUrl: 'https://www.scientificamerican.com/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_sports_cbssports',
    tab: 'foryou',
    label: 'CBS Sports',
    feedUrl: 'https://www.cbssports.com/rss/headlines/',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_entertainment_gamesradar',
    tab: 'foryou',
    label: 'GamesRadar+',
    feedUrl: 'https://www.gamesradar.com/rss/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 83,
  },
  {
    id: 'foryou_education_insidehighered',
    tab: 'foryou',
    label: 'Inside Higher Ed',
    feedUrl: 'https://www.insidehighered.com/rss.xml',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_theatlantic',
    tab: 'foryou',
    label: 'The Atlantic',
    feedUrl: 'https://www.theatlantic.com/feed/all/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 90,
  },

  {
    id: 'foryou_politics_propublica',
    tab: 'foryou',
    label: 'ProPublica',
    feedUrl: 'https://feeds.propublica.org/propublica/main',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_company_yahoofinance',
    tab: 'foryou',
    label: 'Yahoo Finance',
    feedUrl: 'https://finance.yahoo.com/news/rssindex',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_world_euronews',
    tab: 'foryou',
    label: 'Euronews',
    feedUrl: 'https://www.euronews.com/rss?level=theme&name=news',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_tech_androidauthority',
    tab: 'foryou',
    label: 'Android Authority',
    feedUrl: 'https://www.androidauthority.com/feed',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_startups_entrepreneur',
    tab: 'foryou',
    label: 'Entrepreneur',
    feedUrl: 'https://www.entrepreneur.com/latest.rss',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_health_medicalnewstoday',
    tab: 'foryou',
    label: 'Medical News Today',
    feedUrl: 'https://www.medicalnewstoday.com/rss',
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_sports_formula1',
    tab: 'foryou',
    label: 'Formula 1',
    feedUrl: 'https://www.formula1.com/en/latest/all.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_entertainment_thewrap',
    tab: 'foryou',
    label: 'TheWrap',
    feedUrl: 'https://www.thewrap.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_education_timeshighereducation',
    tab: 'foryou',
    label: 'Times Higher Education',
    feedUrl: 'https://www.timeshighereducation.com/rss/news.xml',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_culture_mashable',
    tab: 'foryou',
    label: 'Mashable',
    feedUrl: 'https://mashable.com/feeds/rss/all',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_politics_pbs',
    tab: 'foryou',
    label: 'PBS NewsHour',
    feedUrl: 'https://www.pbs.org/newshour/feeds/rss/headlines',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_fortune',
    tab: 'foryou',
    label: 'Fortune',
    feedUrl: 'https://fortune.com/feed/',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_world_abcnews',
    tab: 'foryou',
    label: 'ABC News',
    feedUrl: 'https://abcnews.go.com/abcnews/topstories',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_tech_zdnet',
    tab: 'foryou',
    label: 'ZDNET',
    feedUrl: 'https://www.zdnet.com/news/rss.xml',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_startups_tnw',
    tab: 'foryou',
    label: 'The Next Web',
    feedUrl: 'https://thenextweb.com/feed',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_health_statnews',
    tab: 'foryou',
    label: 'STAT News',
    feedUrl: 'https://www.statnews.com/feed/',
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_sports_mlb',
    tab: 'foryou',
    label: 'MLB News',
    feedUrl: 'https://www.mlb.com/feeds/news/rss.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_entertainment_people',
    tab: 'foryou',
    label: 'People',
    feedUrl: 'https://people.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_education_educationweek',
    tab: 'foryou',
    label: 'Education Week',
    feedUrl: 'https://www.edweek.org/feeds/education-week-all-topics.xml',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_culture_theconversation',
    tab: 'foryou',
    label: 'The Conversation',
    feedUrl: 'https://theconversation.com/us/articles.atom',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 90,
  },

  {
    id: 'foryou_politics_foreignpolicy',
    tab: 'foryou',
    label: 'Foreign Policy',
    feedUrl: 'https://foreignpolicy.com/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_company_quartz',
    tab: 'foryou',
    label: 'Quartz',
    feedUrl: 'https://qz.com/rss',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_world_usatoday',
    tab: 'foryou',
    label: 'USA Today',
    feedUrl: 'https://rssfeeds.usatoday.com/usatoday-NewsTopStories',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_tech_tomshardware',
    tab: 'foryou',
    label: 'Tom’s Hardware',
    feedUrl: 'https://www.tomshardware.com/feeds/all',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_ai_siliconangle',
    tab: 'foryou',
    label: 'SiliconANGLE',
    feedUrl: 'https://siliconangle.com/feed/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_science_livescience',
    tab: 'foryou',
    label: 'Live Science',
    feedUrl: 'https://www.livescience.com/feeds/all',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_sports_olympics',
    tab: 'foryou',
    label: 'Olympics',
    feedUrl: 'https://olympics.com/en/news/rss',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_entertainment_ew',
    tab: 'foryou',
    label: 'Entertainment Weekly',
    feedUrl: 'https://ew.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_education_campustechnology',
    tab: 'foryou',
    label: 'Campus Technology',
    feedUrl: 'https://campustechnology.com/rss-feeds/all.aspx',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_culture_newyorker',
    tab: 'foryou',
    label: 'The New Yorker',
    feedUrl: 'https://www.newyorker.com/feed/everything',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 89,
  },

  {
    id: 'foryou_politics_brookings',
    tab: 'foryou',
    label: 'Brookings',
    feedUrl: 'https://www.brookings.edu/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_company_inc',
    tab: 'foryou',
    label: 'Inc.',
    feedUrl: 'https://www.inc.com/rss',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_world_nbcnews',
    tab: 'foryou',
    label: 'NBC News',
    feedUrl: 'https://feeds.nbcnews.com/nbcnews/public/news',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_tech_bleepingcomputer',
    tab: 'foryou',
    label: 'BleepingComputer',
    feedUrl: 'https://www.bleepingcomputer.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_ai_thehackernews',
    tab: 'foryou',
    label: 'The Hacker News',
    feedUrl: 'https://feeds.feedburner.com/TheHackersNews',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_science_physorg',
    tab: 'foryou',
    label: 'Phys.org',
    feedUrl: 'https://phys.org/rss-feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_sports_motorsport',
    tab: 'foryou',
    label: 'Motorsport.com',
    feedUrl: 'https://www.motorsport.com/rss/all/news/',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_entertainment_pcgamer',
    tab: 'foryou',
    label: 'PC Gamer',
    feedUrl: 'https://www.pcgamer.com/rss',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_education_chronicle',
    tab: 'foryou',
    label: 'The Chronicle of Higher Education',
    feedUrl: 'https://www.chronicle.com/rss',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_popsci',
    tab: 'foryou',
    label: 'Popular Science',
    feedUrl: 'https://www.popsci.com/feed/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_politics_axios',
    tab: 'foryou',
    label: 'Axios',
    feedUrl: 'https://www.axios.com/feeds/feed.rss',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_forbes',
    tab: 'foryou',
    label: 'Forbes',
    feedUrl: 'https://www.forbes.com/business/feed/',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_world_cbsnews',
    tab: 'foryou',
    label: 'CBS News',
    feedUrl: 'https://www.cbsnews.com/latest/rss/main',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_tech_ieeespectrum',
    tab: 'foryou',
    label: 'IEEE Spectrum',
    feedUrl: 'https://spectrum.ieee.org/rss/fulltext',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_ai_techrepublic',
    tab: 'foryou',
    label: 'TechRepublic',
    feedUrl: 'https://www.techrepublic.com/rssfeeds/topic/artificial-intelligence/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_science_sciencenews',
    tab: 'foryou',
    label: 'Science News',
    feedUrl: 'https://www.sciencenews.org/feed',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_sports_nhl',
    tab: 'foryou',
    label: 'NHL',
    feedUrl: 'https://www.nhl.com/rss/news.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_entertainment_nme',
    tab: 'foryou',
    label: 'NME',
    feedUrl: 'https://www.nme.com/feed',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_education_k12dive',
    tab: 'foryou',
    label: 'K-12 Dive',
    feedUrl: 'https://www.k12dive.com/feeds/news/',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_atlasobscura',
    tab: 'foryou',
    label: 'Atlas Obscura',
    feedUrl: 'https://www.atlasobscura.com/feeds/latest',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 86,
  },

  {
    id: 'foryou_politics_cfr',
    tab: 'foryou',
    label: 'Council on Foreign Relations',
    feedUrl: 'https://www.cfr.org/feed/rss',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_morningstar',
    tab: 'foryou',
    label: 'Morningstar',
    feedUrl: 'https://www.morningstar.com/rss/news',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_world_independent',
    tab: 'foryou',
    label: 'The Independent',
    feedUrl: 'https://www.independent.co.uk/news/world/rss',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_tech_digitaltrends',
    tab: 'foryou',
    label: 'Digital Trends',
    feedUrl: 'https://www.digitaltrends.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_startups_eustartups',
    tab: 'foryou',
    label: 'EU-Startups',
    feedUrl: 'https://www.eu-startups.com/feed/',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_health_medicalxpress',
    tab: 'foryou',
    label: 'Medical Xpress',
    feedUrl: 'https://medicalxpress.com/rss-feed/',
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_sports_tennis',
    tab: 'foryou',
    label: 'Tennis.com',
    feedUrl: 'https://www.tennis.com/news/rss/',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_entertainment_screenrant',
    tab: 'foryou',
    label: 'Screen Rant',
    feedUrl: 'https://screenrant.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_education_highereddive',
    tab: 'foryou',
    label: 'Higher Ed Dive',
    feedUrl: 'https://www.highereddive.com/feeds/news/',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_eater',
    tab: 'foryou',
    label: 'Eater',
    feedUrl: 'https://www.eater.com/rss/index.xml',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 85,
  },

  {
    id: 'foryou_politics_rollcall',
    tab: 'foryou',
    label: 'Roll Call',
    feedUrl: 'https://rollcall.com/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_company_retaildive',
    tab: 'foryou',
    label: 'Retail Dive',
    feedUrl: 'https://www.retaildive.com/feeds/news/',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_world_japantimes',
    tab: 'foryou',
    label: 'The Japan Times',
    feedUrl: 'https://www.japantimes.co.jp/feed/',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_tech_computerworld',
    tab: 'foryou',
    label: 'Computerworld',
    feedUrl: 'https://www.computerworld.com/index.rss',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_ai_artificialintelligencenews',
    tab: 'foryou',
    label: 'AI News',
    feedUrl: 'https://www.artificialintelligence-news.com/feed/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_science_eurekalert',
    tab: 'foryou',
    label: 'EurekAlert!',
    feedUrl: 'https://www.eurekalert.org/rss.xml',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_sports_icc',
    tab: 'foryou',
    label: 'ICC Cricket',
    feedUrl: 'https://www.icc-cricket.com/rss/news',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_entertainment_avclub',
    tab: 'foryou',
    label: 'The A.V. Club',
    feedUrl: 'https://www.avclub.com/rss',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_education_thejournal',
    tab: 'foryou',
    label: 'THE Journal',
    feedUrl: 'https://thejournal.com/rss-feeds/all.aspx',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_culture_mentalfloss',
    tab: 'foryou',
    label: 'Mental Floss',
    feedUrl: 'https://www.mentalfloss.com/rss',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_politics_skynews',
    tab: 'foryou',
    label: 'Sky News',
    feedUrl: 'https://feeds.skynews.com/feeds/rss/home.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_nikkeiasia',
    tab: 'foryou',
    label: 'Nikkei Asia',
    feedUrl: 'https://asia.nikkei.com/rss/feed/nar',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_world_lemonde',
    tab: 'foryou',
    label: 'Le Monde English',
    feedUrl: 'https://www.lemonde.fr/en/rss_full.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_tech_techradar',
    tab: 'foryou',
    label: 'TechRadar',
    feedUrl: 'https://www.techradar.com/rss',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_startups_crunchbasenews',
    tab: 'foryou',
    label: 'Crunchbase News',
    feedUrl: 'https://news.crunchbase.com/feed/',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_science_quanta',
    tab: 'foryou',
    label: 'Quanta Magazine',
    feedUrl: 'https://www.quantamagazine.org/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_sports_cyclingnews',
    tab: 'foryou',
    label: 'Cyclingnews',
    feedUrl: 'https://www.cyclingnews.com/rss',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_entertainment_pitchfork',
    tab: 'foryou',
    label: 'Pitchfork',
    feedUrl: 'https://pitchfork.com/rss/news/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_education_eschoolnews',
    tab: 'foryou',
    label: 'eSchool News',
    feedUrl: 'https://www.eschoolnews.com/feed/',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_culture_aeon',
    tab: 'foryou',
    label: 'Aeon',
    feedUrl: 'https://aeon.co/feed.rss',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 86,
  },

  {
    id: 'foryou_politics_foreignaffairs',
    tab: 'foryou',
    label: 'Foreign Affairs',
    feedUrl: 'https://www.foreignaffairs.com/rss.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_sifted',
    tab: 'foryou',
    label: 'Sifted',
    feedUrl: 'https://sifted.eu/feed',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_world_upi',
    tab: 'foryou',
    label: 'UPI',
    feedUrl: 'https://www.upi.com/rss/news.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_tech_macrumors',
    tab: 'foryou',
    label: 'MacRumors',
    feedUrl: 'https://feeds.macrumors.com/MacRumors-All',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_ai_datanami',
    tab: 'foryou',
    label: 'Datanami',
    feedUrl: 'https://www.datanami.com/feed/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_science_newscientist',
    tab: 'foryou',
    label: 'New Scientist',
    feedUrl: 'https://www.newscientist.com/feed/home/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_sports_sportsillustrated',
    tab: 'foryou',
    label: 'Sports Illustrated',
    feedUrl: 'https://www.si.com/rss/si_topstories.rss',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_entertainment_stereogum',
    tab: 'foryou',
    label: 'Stereogum',
    feedUrl: 'https://www.stereogum.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_education_universityworldnews',
    tab: 'foryou',
    label: 'University World News',
    feedUrl: 'https://www.universityworldnews.com/rss.php',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_lithub',
    tab: 'foryou',
    label: 'Literary Hub',
    feedUrl: 'https://lithub.com/feed/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 85,
  },

  {
    id: 'foryou_politics_thediplomat',
    tab: 'foryou',
    label: 'The Diplomat',
    feedUrl: 'https://thediplomat.com/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_company_finextra',
    tab: 'foryou',
    label: 'Finextra',
    feedUrl: 'https://www.finextra.com/rss/news.aspx',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_world_globalnews',
    tab: 'foryou',
    label: 'Global News',
    feedUrl: 'https://globalnews.ca/feed/',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_tech_slashdot',
    tab: 'foryou',
    label: 'Slashdot',
    feedUrl: 'https://rss.slashdot.org/Slashdot/slashdotMain',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_ai_infoq',
    tab: 'foryou',
    label: 'InfoQ',
    feedUrl: 'https://feed.infoq.com/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_science_astronomy',
    tab: 'foryou',
    label: 'Astronomy Magazine',
    feedUrl: 'https://www.astronomy.com/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_sports_autosport',
    tab: 'foryou',
    label: 'Autosport',
    feedUrl: 'https://www.autosport.com/rss/feed/f1/',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_entertainment_comicbook',
    tab: 'foryou',
    label: 'ComicBook.com',
    feedUrl: 'https://comicbook.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_education_hechinger',
    tab: 'foryou',
    label: 'The Hechinger Report',
    feedUrl: 'https://hechingerreport.org/feed/',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_hyperallergic',
    tab: 'foryou',
    label: 'Hyperallergic',
    feedUrl: 'https://hyperallergic.com/feed/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 85,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BANGLADESH — Bangla
  // ══════════════════════════════════════════════════════════════════════════
    
    {
    id: 'bd_national_prothomalo',
    tab: 'bangladesh',
    label: 'প্রথম আলো',
    feedUrl: 'https://www.prothomalo.com/feed/',
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 100,
    trustScore: 98,
  },
  {
    id: 'bd_world_bbc_bangla',
    tab: 'bangladesh',
    label: 'BBC Bangla',
    feedUrl: 'http://feeds.bbci.co.uk/bengali/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিশ্ব',
    priority: 99,
    trustScore: 98,
  },
  {
    id: 'bd_national_bdnews24_bangla',
    tab: 'bangladesh',
    label: 'বিডিনিউজ২৪ বাংলা',
    feedUrl: 'https://bangla.bdnews24.com/rss',
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 98,
    trustScore: 96,
  },
  {
    id: 'bd_world_dw_bangla',
    tab: 'bangladesh',
    label: 'DW বাংলা',
    feedUrl: 'https://rss.dw.com/rdf/rss-ben-all',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিশ্ব',
    priority: 97,
    trustScore: 95,
  },
  {
    id: 'bd_politics_banglatribune',
    tab: 'bangladesh',
    label: 'বাংলা ট্রিবিউন',
    feedUrl: 'https://www.banglatribune.com/feed',
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 96,
    trustScore: 94,
  },
  {
    id: 'bd_business_tbs_bangla',
    tab: 'bangladesh',
    label: 'দ্য বিজনেস স্ট্যান্ডার্ড বাংলা',
    feedUrl: 'https://www.tbsnews.net/bangla/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 95,
    trustScore: 93,
  },
  {
    id: 'bd_sports_jagonews24',
    tab: 'bangladesh',
    label: 'জাগোনিউজ২৪',
    feedUrl: 'https://www.jagonews24.com/rss/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'খেলা',
    priority: 94,
    trustScore: 92,
  },
  {
    id: 'bd_education_dailycampus',
    tab: 'bangladesh',
    label: 'দ্য ডেইলি ক্যাম্পাস',
    feedUrl: 'https://thedailycampus.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'শিক্ষা',
    priority: 93,
    trustScore: 91,
  },
  {
    id: 'bd_tech_banglanews24',
    tab: 'bangladesh',
    label: 'বাংলানিউজ২৪',
    feedUrl: 'https://www.banglanews24.com/rss/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'প্রযুক্তি',
    priority: 92,
    trustScore: 90,
  },
  {
    id: 'bd_lifestyle_ajkerpatrika',
    tab: 'bangladesh',
    label: 'আজকের পত্রিকা',
    feedUrl: 'https://www.ajkerpatrika.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'জীবনযাপন',
    priority: 91,
    trustScore: 90,
  },

  {
    id: 'bd_national_dhakapost',
    tab: 'bangladesh',
    label: 'ঢাকা পোস্ট',
    feedUrl: 'https://www.dhakapost.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 90,
    trustScore: 90,
  },
  {
    id: 'bd_world_voa_bangla',
    tab: 'bangladesh',
    label: 'VOA বাংলা',
    feedUrl: 'https://www.voabangla.com/api/zrqiteuuir',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিশ্ব',
    priority: 89,
    trustScore: 92,
  },
  {
    id: 'bd_politics_samakal',
    tab: 'bangladesh',
    label: 'সমকাল',
    feedUrl: 'https://samakal.com/rss/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 88,
    trustScore: 90,
  },
  {
    id: 'bd_business_bonikbarta',
    tab: 'bangladesh',
    label: 'বণিক বার্তা',
    feedUrl: 'https://bonikbarta.net/feed',
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 87,
    trustScore: 90,
  },
  {
    id: 'bd_tech_ittefaq',
    tab: 'bangladesh',
    label: 'ইত্তেফাক',
    feedUrl: 'https://www.ittefaq.com.bd/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'প্রযুক্তি',
    priority: 86,
    trustScore: 89,
  },
  {
    id: 'bd_sports_bd_pratidin',
    tab: 'bangladesh',
    label: 'বাংলাদেশ প্রতিদিন',
    feedUrl: 'https://www.bd-pratidin.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'খেলা',
    priority: 85,
    trustScore: 89,
  },
  {
    id: 'bd_entertainment_jugantor',
    tab: 'bangladesh',
    label: 'যুগান্তর',
    feedUrl: 'https://www.jugantor.com/feed/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিনোদন',
    priority: 84,
    trustScore: 89,
  },
  {
    id: 'bd_health_kalerkantho',
    tab: 'bangladesh',
    label: 'কালের কণ্ঠ',
    feedUrl: 'https://www.kalerkantho.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'স্বাস্থ্য',
    priority: 83,
    trustScore: 89,
  },
  {
    id: 'bd_education_dainikshiksha',
    tab: 'bangladesh',
    label: 'দৈনিক শিক্ষা',
    feedUrl: 'https://www.dainikshiksha.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'শিক্ষা',
    priority: 82,
    trustScore: 88,
  },
  {
    id: 'bd_lifestyle_kalbela',
    tab: 'bangladesh',
    label: 'কালবেলা',
    feedUrl: 'https://www.kalbela.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'জীবনযাপন',
    priority: 81,
    trustScore: 88,
  },

  {
    id: 'bd_national_bss_bangla',
    tab: 'bangladesh',
    label: 'বাসস বাংলা',
    feedUrl: 'https://www.bssnews.net/bangla/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 80,
    trustScore: 91,
  },
  {
    id: 'bd_world_unb_bangla',
    tab: 'bangladesh',
    label: 'ইউএনবি বাংলা',
    feedUrl: 'https://unb.com.bd/bangla/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিশ্ব',
    priority: 79,
    trustScore: 90,
  },
  {
    id: 'bd_politics_manabzamin',
    tab: 'bangladesh',
    label: 'মানবজমিন',
    feedUrl: 'https://mzamin.com/rss.php',
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 78,
    trustScore: 87,
  },
  {
    id: 'bd_business_sharebiz',
    tab: 'bangladesh',
    label: 'শেয়ার বিজ',
    feedUrl: 'https://sharebiz.net/feed',
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 77,
    trustScore: 86,
  },
  {
    id: 'bd_tech_risingbd',
    tab: 'bangladesh',
    label: 'রাইজিংবিডি',
    feedUrl: 'https://www.risingbd.com/rss/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'প্রযুক্তি',
    priority: 76,
    trustScore: 87,
  },
  {
    id: 'bd_sports_daily_nayadiganta',
    tab: 'bangladesh',
    label: 'নয়া দিগন্ত',
    feedUrl: 'https://www.dailynayadiganta.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'খেলা',
    priority: 75,
    trustScore: 86,
  },
  {
    id: 'bd_entertainment_deshrupantor',
    tab: 'bangladesh',
    label: 'দেশ রূপান্তর',
    feedUrl: 'https://www.deshrupantor.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিনোদন',
    priority: 74,
    trustScore: 86,
  },
  {
    id: 'bd_health_barta24',
    tab: 'bangladesh',
    label: 'বার্তা২৪',
    feedUrl: 'https://barta24.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'স্বাস্থ্য',
    priority: 73,
    trustScore: 86,
  },
  {
    id: 'bd_education_shikshabarta',
    tab: 'bangladesh',
    label: 'শিক্ষা বার্তা',
    feedUrl: 'https://shikshabarta.com/feed/',
    language: 'bn',
    region: 'bangladesh',
    category: 'শিক্ষা',
    priority: 72,
    trustScore: 84,
  },
  {
    id: 'bd_lifestyle_sarabangla',
    tab: 'bangladesh',
    label: 'সারাবাংলা',
    feedUrl: 'https://sarabangla.net/feed/',
    language: 'bn',
    region: 'bangladesh',
    category: 'জীবনযাপন',
    priority: 71,
    trustScore: 85,
  },

  {
    id: 'bd_national_bd24live',
    tab: 'bangladesh',
    label: 'বিডি২৪লাইভ',
    feedUrl: 'https://www.bd24live.com/bangla/feed',
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 70,
    trustScore: 85,
  },
  {
    id: 'bd_world_news18_bengali',
    tab: 'bangladesh',
    label: 'News18 বাংলা',
    feedUrl: 'https://bengali.news18.com/rss/',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিশ্ব',
    priority: 69,
    trustScore: 86,
  },
  {
    id: 'bd_politics_inqilab',
    tab: 'bangladesh',
    label: 'ইনকিলাব',
    feedUrl: 'https://dailyinqilab.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 68,
    trustScore: 84,
  },
  {
    id: 'bd_business_dailybangladesh',
    tab: 'bangladesh',
    label: 'ডেইলি বাংলাদেশ',
    feedUrl: 'https://www.daily-bangladesh.com/rss/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 67,
    trustScore: 84,
  },
  {
    id: 'bd_tech_dailystar_bangla',
    tab: 'bangladesh',
    label: 'দ্য ডেইলি স্টার বাংলা',
    feedUrl: 'https://bangla.thedailystar.net/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'প্রযুক্তি',
    priority: 66,
    trustScore: 87,
  },
  {
    id: 'bd_sports_amadershomoy',
    tab: 'bangladesh',
    label: 'আমাদের সময়',
    feedUrl: 'https://www.amadershomoy.com/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'খেলা',
    priority: 65,
    trustScore: 84,
  },
  {
    id: 'bd_entertainment_bdjournal',
    tab: 'bangladesh',
    label: 'বাংলাদেশ জার্নাল',
    feedUrl: 'https://www.bd-journal.com/feed/latest-rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'বিনোদন',
    priority: 64,
    trustScore: 84,
  },
  {
    id: 'bd_health_channeli',
    tab: 'bangladesh',
    label: 'চ্যানেল আই',
    feedUrl: 'https://www.channelionline.com/feed/',
    language: 'bn',
    region: 'bangladesh',
    category: 'স্বাস্থ্য',
    priority: 63,
    trustScore: 84,
  },
  {
    id: 'bd_education_jagonews_education',
    tab: 'bangladesh',
    label: 'শিক্ষা খবর',
    feedUrl: 'https://www.jagonews24.com/rss/education',
    language: 'bn',
    region: 'bangladesh',
    category: 'শিক্ষা',
    priority: 62,
    trustScore: 84,
  },
  {
    id: 'bd_lifestyle_ittefaq_lifestyle',
    tab: 'bangladesh',
    label: 'লাইফস্টাইল খবর',
    feedUrl: 'https://www.ittefaq.com.bd/rss.xml',
    language: 'bn',
    region: 'bangladesh',
    category: 'জীবনযাপন',
    priority: 61,
    trustScore: 84,
  },
    
];

// ── Exported helper ───────────────────────────────────────────────────────────

export function getDiscoverSources(tab: DiscoverTab): DiscoverSource[] {
  return DISCOVER_SOURCES
    .filter((source) => source.tab === tab)
    .sort((a, b) => b.priority - a.priority || b.trustScore - a.trustScore);
    }
