// ASK-GPT Discover — Trusted Source List
// api/_lib/discoverSources.ts
// Only source definitions. No fetching, parsing, or caching here.

// ── Types ─────────────────────────────────────────────────────────────────────

export type DiscoverTab = 'foryou' | 'bangladesh';
export type DiscoverLanguage = 'en' | 'bn';
export type DiscoverRegion = 'global' | 'bangladesh';

export type DiscoverSource = {
  id: string;
  tab: DiscoverTab;
  label: string;
  feedUrl: string;
  language: DiscoverLanguage;
  region: DiscoverRegion;
  category: string;
  priority: number;
  trustScore: number;
};

// ── Google News RSS helper ────────────────────────────────────────────────────

function googleNewsSearch(
  query: string,
  options: { language: DiscoverLanguage; region: DiscoverRegion },
): string {
  if (options.language === 'bn') {
    return `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=bn&gl=BD&ceid=BD:bn`;
  }
  return `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US:en`;
}

// ── Source List ───────────────────────────────────────────────────────────────

export const DISCOVER_SOURCES: DiscoverSource[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // FOR YOU — Global English
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'foryou_world_reuters',
    tab: 'foryou',
    label: 'Reuters — World News',
    feedUrl: 'https://feeds.reuters.com/reuters/topNews',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 100,
    trustScore: 98,
  },
  {
    id: 'foryou_world_bbc',
    tab: 'foryou',
    label: 'BBC News — World',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 99,
    trustScore: 97,
  },
  {
    id: 'foryou_world_ap',
    tab: 'foryou',
    label: 'AP News — Top Stories',
    feedUrl: googleNewsSearch('site:apnews.com', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 98,
    trustScore: 97,
  },
  {
    id: 'foryou_tech_verge',
    tab: 'foryou',
    label: 'The Verge — Technology',
    feedUrl: 'https://www.theverge.com/rss/index.xml',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 95,
    trustScore: 93,
  },
  {
    id: 'foryou_tech_techcrunch',
    tab: 'foryou',
    label: 'TechCrunch',
    feedUrl: 'https://techcrunch.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 94,
    trustScore: 92,
  },
  {
    id: 'foryou_ai_wired',
    tab: 'foryou',
    label: 'Wired — AI & Science',
    feedUrl: 'https://www.wired.com/feed/rss',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 93,
    trustScore: 91,
  },
  {
    id: 'foryou_ai_gnews',
    tab: 'foryou',
    label: 'Google News — Artificial Intelligence',
    feedUrl: googleNewsSearch('artificial intelligence AI OpenAI Google DeepMind', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 92,
    trustScore: 88,
  },
  {
    id: 'foryou_business_bloomberg',
    tab: 'foryou',
    label: 'Bloomberg — Business',
    feedUrl: googleNewsSearch('site:bloomberg.com business economy', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 91,
    trustScore: 95,
  },
  {
    id: 'foryou_finance_cnbc',
    tab: 'foryou',
    label: 'CNBC — Markets & Finance',
    feedUrl: 'https://www.cnbc.com/id/100003114/device/rss/rss.html',
    language: 'en',
    region: 'global',
    category: 'finance',
    priority: 90,
    trustScore: 93,
  },
  {
    id: 'foryou_science_daily',
    tab: 'foryou',
    label: 'ScienceDaily — Top Science',
    feedUrl: 'https://www.sciencedaily.com/rss/top/science.xml',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 88,
    trustScore: 90,
  },
  {
    id: 'foryou_health_who',
    tab: 'foryou',
    label: 'Google News — Health & Medicine',
    feedUrl: googleNewsSearch('health medicine WHO CDC disease treatment', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 87,
    trustScore: 88,
  },
  {
    id: 'foryou_sports_espn',
    tab: 'foryou',
    label: 'ESPN — Sports',
    feedUrl: 'https://www.espn.com/espn/rss/news',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 86,
    trustScore: 90,
  },
  {
    id: 'foryou_entertainment_variety',
    tab: 'foryou',
    label: 'Variety — Entertainment',
    feedUrl: 'https://variety.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 84,
    trustScore: 87,
  },
  {
    id: 'foryou_culture_gnews',
    tab: 'foryou',
    label: 'Google News — Culture & Society',
    feedUrl: googleNewsSearch('culture society lifestyle trending stories', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 82,
    trustScore: 82,
  },
  {
    id: 'foryou_climate_gnews',
    tab: 'foryou',
    label: 'Google News — Climate & Environment',
    feedUrl: googleNewsSearch('climate change environment nature sustainability', { language: 'en', region: 'global' }),
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 80,
    trustScore: 85,
  },
  {
    id: 'foryou_world_bbc_frontpage',
    tab: 'foryou',
    label: 'BBC News — Top Stories',
    feedUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 95,
  },
  {
    id: 'foryou_world_bbc_world',
    tab: 'foryou',
    label: 'BBC News — World',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 95,
  },
  {
    id: 'foryou_world_guardian',
    tab: 'foryou',
    label: 'The Guardian — World',
    feedUrl: 'https://www.theguardian.com/world/rss',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 94,
  },
  {
    id: 'foryou_business_guardian',
    tab: 'foryou',
    label: 'The Guardian — Business',
    feedUrl: 'https://www.theguardian.com/business/rss',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 93,
  },
  {
    id: 'foryou_tech_guardian',
    tab: 'foryou',
    label: 'The Guardian — Technology',
    feedUrl: 'https://www.theguardian.com/technology/rss',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_science_guardian',
    tab: 'foryou',
    label: 'The Guardian — Science',
    feedUrl: 'https://www.theguardian.com/science/rss',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_sports_guardian',
    tab: 'foryou',
    label: 'The Guardian — Sport',
    feedUrl: 'https://www.theguardian.com/sport/rss',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_culture_guardian',
    tab: 'foryou',
    label: 'The Guardian — Culture',
    feedUrl: 'https://www.theguardian.com/culture/rss',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_education_guardian',
    tab: 'foryou',
    label: 'The Guardian — Education',
    feedUrl: 'https://www.theguardian.com/education/rss',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_climate_guardian',
    tab: 'foryou',
    label: 'The Guardian — Environment',
    feedUrl: 'https://www.theguardian.com/environment/rss',
    language: 'en',
    region: 'global',
    category: 'climate',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_world_aljazeera_all',
    tab: 'foryou',
    label: 'Al Jazeera — Latest',
    feedUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_world_dw_all',
    tab: 'foryou',
    label: 'DW — Latest',
    feedUrl: 'https://rss.dw.com/rdf/rss-en-all',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_world_france24',
    tab: 'foryou',
    label: 'France 24 — English',
    feedUrl: 'https://www.france24.com/en/rss',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_world_npr_news',
    tab: 'foryou',
    label: 'NPR — News',
    feedUrl: 'https://feeds.npr.org/1001/rss.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_politics_npr',
    tab: 'foryou',
    label: 'NPR — Politics',
    feedUrl: 'https://feeds.npr.org/1014/rss.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_tech_engadget',
    tab: 'foryou',
    label: 'Engadget — Technology',
    feedUrl: 'https://www.engadget.com/rss.xml',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_tech_arstechnica',
    tab: 'foryou',
    label: 'Ars Technica',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/index',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_ai_venturebeat',
    tab: 'foryou',
    label: 'VentureBeat — AI',
    feedUrl: 'https://venturebeat.com/category/ai/feed/',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_science_sciencedaily',
    tab: 'foryou',
    label: 'ScienceDaily — Top Science',
    feedUrl: 'https://www.sciencedaily.com/rss/top/science.xml',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_science_space',
    tab: 'foryou',
    label: 'Space.com',
    feedUrl: 'https://www.space.com/feeds/all',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_sports_bbc',
    tab: 'foryou',
    label: 'BBC Sport',
    feedUrl: 'https://feeds.bbci.co.uk/sport/rss.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 91,
  },
  {
    id: 'foryou_sports_espncricinfo',
    tab: 'foryou',
    label: 'ESPN Cricinfo',
    feedUrl: 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_sports_espn',
    tab: 'foryou',
    label: 'ESPN — Sports',
    feedUrl: 'https://www.espn.com/espn/rss/news',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_entertainment_variety',
    tab: 'foryou',
    label: 'Variety — Entertainment',
    feedUrl: 'https://variety.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_entertainment_hollywoodreporter',
    tab: 'foryou',
    label: 'The Hollywood Reporter',
    feedUrl: 'https://www.hollywoodreporter.com/t/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_entertainment_deadline',
    tab: 'foryou',
    label: 'Deadline — Entertainment',
    feedUrl: 'https://deadline.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_music_rollingstone',
    tab: 'foryou',
    label: 'Rolling Stone',
    feedUrl: 'https://www.rollingstone.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_gaming_ign',
    tab: 'foryou',
    label: 'IGN — Gaming',
    feedUrl: 'https://feeds.ign.com/ign/all',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_culture_smithsonian',
    tab: 'foryou',
    label: 'Smithsonian Magazine',
    feedUrl: 'https://www.smithsonianmag.com/rss/latest_articles/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_career_hbr',
    tab: 'foryou',
    label: 'Harvard Business Review',
    feedUrl: 'https://hbr.org/feed',
    language: 'en',
    region: 'global',
    category: 'careers',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_politics_politico',
    tab: 'foryou',
    label: 'Politico',
    feedUrl: 'https://www.politico.com/rss/politicopicks.xml',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_company_wsj',
    tab: 'foryou',
    label: 'The Wall Street Journal',
    feedUrl: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_world_time',
    tab: 'foryou',
    label: 'TIME',
    feedUrl: 'https://rss.time.com/web/time/rss/top/index.xml',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_tech_mitnews',
    tab: 'foryou',
    label: 'MIT News',
    feedUrl: 'https://news.mit.edu/rss/feed',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_ai_fastcompany',
    tab: 'foryou',
    label: 'Fast Company',
    feedUrl: 'https://www.fastcompany.com/rss',
    language: 'en',
    region: 'global',
    category: 'ai',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_science_nasa',
    tab: 'foryou',
    label: 'NASA',
    feedUrl: 'https://www.nasa.gov/news-release/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 92,
  },
  {
    id: 'foryou_sports_skysports',
    tab: 'foryou',
    label: 'Sky Sports',
    feedUrl: 'https://www.skysports.com/rss/12040',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_entertainment_billboard',
    tab: 'foryou',
    label: 'Billboard',
    feedUrl: 'https://www.billboard.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_education_edsurge',
    tab: 'foryou',
    label: 'EdSurge',
    feedUrl: 'https://www.edsurge.com/articles_rss',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_vox',
    tab: 'foryou',
    label: 'Vox',
    feedUrl: 'https://www.vox.com/rss/index.xml',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 88,
  },

  {
    id: 'foryou_politics_thehill',
    tab: 'foryou',
    label: 'The Hill',
    feedUrl: 'https://thehill.com/feed/',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_company_marketwatch',
    tab: 'foryou',
    label: 'MarketWatch',
    feedUrl: 'https://feeds.marketwatch.com/marketwatch/topstories/',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_world_cbc',
    tab: 'foryou',
    label: 'CBC News',
    feedUrl: 'https://www.cbc.ca/cmlink/rss-topstories',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_tech_9to5google',
    tab: 'foryou',
    label: '9to5Google',
    feedUrl: 'https://9to5google.com/feed/',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_startups_businessinsider',
    tab: 'foryou',
    label: 'Business Insider',
    feedUrl: 'https://www.businessinsider.com/rss',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_science_scientificamerican',
    tab: 'foryou',
    label: 'Scientific American',
    feedUrl: 'https://www.scientificamerican.com/feed/',
    language: 'en',
    region: 'global',
    category: 'science',
    priority: 50,
    trustScore: 89,
  },
  {
    id: 'foryou_sports_cbssports',
    tab: 'foryou',
    label: 'CBS Sports',
    feedUrl: 'https://www.cbssports.com/rss/headlines/',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 85,
  },
  {
    id: 'foryou_entertainment_gamesradar',
    tab: 'foryou',
    label: 'GamesRadar+',
    feedUrl: 'https://www.gamesradar.com/rss/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 83,
  },
  {
    id: 'foryou_education_insidehighered',
    tab: 'foryou',
    label: 'Inside Higher Ed',
    feedUrl: 'https://www.insidehighered.com/rss.xml',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_culture_theatlantic',
    tab: 'foryou',
    label: 'The Atlantic',
    feedUrl: 'https://www.theatlantic.com/feed/all/',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 90,
  },

  {
    id: 'foryou_politics_propublica',
    tab: 'foryou',
    label: 'ProPublica',
    feedUrl: 'https://feeds.propublica.org/propublica/main',
    language: 'en',
    region: 'global',
    category: 'politics',
    priority: 50,
    trustScore: 88,
  },
  {
    id: 'foryou_company_yahoofinance',
    tab: 'foryou',
    label: 'Yahoo Finance',
    feedUrl: 'https://finance.yahoo.com/news/rssindex',
    language: 'en',
    region: 'global',
    category: 'business',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_world_euronews',
    tab: 'foryou',
    label: 'Euronews',
    feedUrl: 'https://www.euronews.com/rss?level=theme&name=news',
    language: 'en',
    region: 'global',
    category: 'world',
    priority: 50,
    trustScore: 87,
  },
  {
    id: 'foryou_tech_androidauthority',
    tab: 'foryou',
    label: 'Android Authority',
    feedUrl: 'https://www.androidauthority.com/feed',
    language: 'en',
    region: 'global',
    category: 'technology',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_startups_entrepreneur',
    tab: 'foryou',
    label: 'Entrepreneur',
    feedUrl: 'https://www.entrepreneur.com/latest.rss',
    language: 'en',
    region: 'global',
    category: 'startups',
    priority: 50,
    trustScore: 84,
  },
  {
    id: 'foryou_health_medicalnewstoday',
    tab: 'foryou',
    label: 'Medical News Today',
    feedUrl: 'https://www.medicalnewstoday.com/rss',
    language: 'en',
    region: 'global',
    category: 'health',
    priority: 50,
    trustScore: 86,
  },
  {
    id: 'foryou_sports_formula1',
    tab: 'foryou',
    label: 'Formula 1',
    feedUrl: 'https://www.formula1.com/en/latest/all.xml',
    language: 'en',
    region: 'global',
    category: 'sports',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_entertainment_thewrap',
    tab: 'foryou',
    label: 'TheWrap',
    feedUrl: 'https://www.thewrap.com/feed/',
    language: 'en',
    region: 'global',
    category: 'entertainment',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_education_timeshighereducation',
    tab: 'foryou',
    label: 'Times Higher Education',
    feedUrl: 'https://www.timeshighereducation.com/rss/news.xml',
    language: 'en',
    region: 'global',
    category: 'education',
    priority: 50,
    trustScore: 90,
  },
  {
    id: 'foryou_culture_mashable',
    tab: 'foryou',
    label: 'Mashable',
    feedUrl: 'https://mashable.com/feeds/rss/all',
    language: 'en',
    region: 'global',
    category: 'culture',
    priority: 50,
    trustScore: 90,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BANGLADESH — Bangla
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'bd_national_prothomalo',
    tab: 'bangladesh',
    label: 'প্রথম আলো — জাতীয়',
    feedUrl: googleNewsSearch('প্রথম আলো বাংলাদেশ জাতীয় সংবাদ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 100,
    trustScore: 97,
  },
  {
    id: 'bd_national_bdnews24',
    tab: 'bangladesh',
    label: 'বিডিনিউজ২৪ — শীর্ষ সংবাদ',
    feedUrl: googleNewsSearch('site:bangla.bdnews24.com বাংলাদেশ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 99,
    trustScore: 96,
  },
  {
    id: 'bd_national_banglatribune',
    tab: 'bangladesh',
    label: 'বাংলা ট্রিবিউন — জাতীয়',
    feedUrl: googleNewsSearch('বাংলা ট্রিবিউন বাংলাদেশ সংবাদ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 98,
    trustScore: 94,
  },
  {
    id: 'bd_politics_jugantor',
    tab: 'bangladesh',
    label: 'যুগান্তর — রাজনীতি',
    feedUrl: googleNewsSearch('যুগান্তর বাংলাদেশ রাজনীতি', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 95,
    trustScore: 91,
  },
  {
    id: 'bd_politics_samakal',
    tab: 'bangladesh',
    label: 'সমকাল — রাজনীতি ও জাতীয়',
    feedUrl: googleNewsSearch('সমকাল বাংলাদেশ রাজনীতি সরকার', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'রাজনীতি',
    priority: 94,
    trustScore: 90,
  },
  {
    id: 'bd_economy_kalerkantho',
    tab: 'bangladesh',
    label: 'কালের কণ্ঠ — অর্থনীতি',
    feedUrl: googleNewsSearch('কালের কণ্ঠ বাংলাদেশ অর্থনীতি ব্যবসা', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 93,
    trustScore: 90,
  },
  {
    id: 'bd_economy_gnews',
    tab: 'bangladesh',
    label: 'Google News — বাংলাদেশ অর্থনীতি',
    feedUrl: googleNewsSearch('বাংলাদেশ অর্থনীতি বাজেট বিনিয়োগ শেয়ার বাজার', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'অর্থনীতি',
    priority: 92,
    trustScore: 87,
  },
  {
    id: 'bd_tech_gnews',
    tab: 'bangladesh',
    label: 'Google News — প্রযুক্তি ও ICT',
    feedUrl: googleNewsSearch('বাংলাদেশ প্রযুক্তি ICT ডিজিটাল স্টার্টআপ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'প্রযুক্তি',
    priority: 91,
    trustScore: 86,
  },
  {
    id: 'bd_sports_gnews',
    tab: 'bangladesh',
    label: 'Google News — বাংলাদেশ ক্রিকেট ও খেলা',
    feedUrl: googleNewsSearch('বাংলাদেশ ক্রিকেট ফুটবল খেলাধুলা', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'খেলা',
    priority: 90,
    trustScore: 88,
  },
  {
    id: 'bd_entertainment_gnews',
    tab: 'bangladesh',
    label: 'Google News — বিনোদন',
    feedUrl: googleNewsSearch('বাংলাদেশ বিনোদন চলচ্চিত্র নাটক সংগীত', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'বিনোদন',
    priority: 88,
    trustScore: 83,
  },
  {
    id: 'bd_health_gnews',
    tab: 'bangladesh',
    label: 'Google News — স্বাস্থ্য',
    feedUrl: googleNewsSearch('বাংলাদেশ স্বাস্থ্য হাসপাতাল রোগ চিকিৎসা', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'স্বাস্থ্য',
    priority: 87,
    trustScore: 85,
  },
  {
    id: 'bd_education_gnews',
    tab: 'bangladesh',
    label: 'Google News — শিক্ষা',
    feedUrl: googleNewsSearch('বাংলাদেশ শিক্ষা বিশ্ববিদ্যালয় এসএসসি এইচএসসি পরীক্ষা', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'শিক্ষা',
    priority: 86,
    trustScore: 86,
  },
  {
    id: 'bd_dhaka_gnews',
    tab: 'bangladesh',
    label: 'Google News — ঢাকা শহর',
    feedUrl: googleNewsSearch('ঢাকা শহর যানজট উন্নয়ন নগর', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'শহর',
    priority: 84,
    trustScore: 82,
  },
  {
    id: 'bd_ittefaq',
    tab: 'bangladesh',
    label: 'ইত্তেফাক — সর্বশেষ',
    feedUrl: googleNewsSearch('ইত্তেফাক বাংলাদেশ সর্বশেষ সংবাদ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 83,
    trustScore: 88,
  },
  {
    id: 'bd_jamuna_tv',
    tab: 'bangladesh',
    label: 'যমুনা টিভি — সংবাদ',
    feedUrl: googleNewsSearch('যমুনা টিভি বাংলাদেশ সংবাদ', { language: 'bn', region: 'bangladesh' }),
    language: 'bn',
    region: 'bangladesh',
    category: 'জাতীয়',
    priority: 82,
    trustScore: 87,
  },
];

// ── Exported helper ───────────────────────────────────────────────────────────

export function getDiscoverSources(tab: DiscoverTab): DiscoverSource[] {
  return DISCOVER_SOURCES
    .filter((source) => source.tab === tab)
    .sort((a, b) => b.priority - a.priority || b.trustScore - a.trustScore);
    }
